const perform = async (z, bundle) => {
  return [bundle.cleanedRequest];
};

module.exports = {
  operation: {
    perform: perform,
    inputFields: [
      {
        key: 'address',
        type: 'string',
        label: 'Contract Address',
        helpText:
          'a contract address or a list of addresses from which logs should originate.',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'topics',
        type: 'string',
        label: 'Topics',
        helpText: 'Array of 32 Bytes DATA topics. Topics are order-dependent',
        required: false,
        list: true,
        altersDynamicFields: false,
      }
    ],
    type: 'hook',
    performList: {
      headers: {
        Accept: 'application/json',
        'X-RPC-PROVIDER': '{{bundle.authData.rpc_provider}}',
        'X-PROVIDER-KEY': '{{bundle.authData.provider_key}}',
      },
      params: {
        rpc_provider: '{{bundle.authData.rpc_provider}}',
        provider_key: '{{bundle.authData.provider_key}}',
        address: '{{bundle.inputData.address}}',
        topics: '{{bundle.inputData.topics}}',
      },
      url: `https://web3hooks.leopapais.com/events`,
    },
    performSubscribe: {
      body: {
        hookUrl: '{{bundle.targetUrl}}',
        address: '{{bundle.inputData.address}}',
        topics: '{{bundle.inputData.topics}}',
      },
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
        'X-RPC-PROVIDER': '{{bundle.authData.rpc_provider}}',
        'X-PROVIDER-KEY': '{{bundle.authData.provider_key}}',
      },
      method: 'POST',
      params: {
        rpc_provider: '{{bundle.authData.rpc_provider}}',
        provider_key: '{{bundle.authData.provider_key}}',
      },
      removeMissingValuesFrom: { params: false, body: true },
      url: `https://web3hooks.leopapais.com/events`,
    },
    performUnsubscribe: {
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
        'X-RPC-PROVIDER': '{{bundle.authData.rpc_provider}}',
        'X-PROVIDER-KEY': '{{bundle.authData.provider_key}}',
      },
      method: 'DELETE',
      params: {
        rpc_provider: '{{bundle.authData.rpc_provider}}',
        provider_key: '{{bundle.authData.provider_key}}',
        zap_id: '{{bundle.subscribeData.zapId}}',
      },
      url: `https://web3hooks.leopapais.com/events`,
    },
    sample: {
      blockNumber: 16101175,
      blockHash:
        '0x8c85e89e89fbee4cdfa60a608a6a406cdfa3ddcd6b82ba47638f380b6e12fa22',
      transactionIndex: 38,
      removed: false,
      address: '0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84',
      data: '0x00000000000000000000000000000000000000000000000000343a28a6167414',
      topics: [
        '0x9d9c909296d9c674451c0c24f02cb64981eb3b727f99865939192f880a755dcb',
        '0x0000000000000000000000000000000000000000000000000000000000000000',
        '0x0000000000000000000000006bef03f5f9766ed8306456a47562c891657fa9bb',
      ],
      transactionHash:
        '0xde4801bee6e2b579e2da327d6c291424ee180aca8f5b9d1a89706ef04b1f5b37',
      logIndex: 192,
    },
    outputFields: [
      { key: 'blockNumber', type: 'number' },
      { key: 'blockHash' },
      { key: 'transactionIndex', type: 'number' },
      { key: 'removed', type: 'boolean' },
      { key: 'address' },
      { key: 'data' },
      { key: 'topics[]0', type: 'string' },
      { key: 'topics[]1' },
      { key: 'topics[]2' },
      { key: 'topics[]3' },
      { key: 'topics[]4' },
      { key: 'topics[]5' },
      { key: 'topics[]6' },
      { key: 'topics[]7' },
      { key: 'topics[]8' },
      { key: 'topics[]9' },
      { key: 'topics[]10' },
      { key: 'topics[]11' },
      { key: 'topics[]12' },
      { key: 'topics[]13' },
      { key: 'topics[]14' },
      { key: 'topics[]15' },
      { key: 'topics[]16' },
      { key: 'topics[]17' },
      { key: 'topics[]18' },
      { key: 'topics[]19' },
      { key: 'topics[]20' },
      { key: 'topics[]21' },
      { key: 'topics[]22' },
      { key: 'topics[]23' },
      { key: 'topics[]24' },
      { key: 'topics[]25' },
      { key: 'topics[]26' },
      { key: 'topics[]27' },
      { key: 'topics[]28' },
      { key: 'topics[]29' },
      { key: 'topics[]30' },
      { key: 'topics[]31' },
      { key: 'topics[]32' },
      { key: 'topics[]33' },
      { key: 'topics[]34' },
      { key: 'topics[]35' },
      { key: 'topics[]36' },
      { key: 'topics[]37' },
      { key: 'topics[]38' },
      { key: 'topics[]39' },
      { key: 'topics[]40' },
      { key: 'topics[]41' },
      { key: 'topics[]42' },
      { key: 'topics[]43' },
      { key: 'topics[]44' },
      { key: 'topics[]45' },
      { key: 'topics[]46' },
      { key: 'topics[]47' },
      { key: 'topics[]48' },
      { key: 'topics[]49' },
      { key: 'topics[]50' },
      { key: 'topics[]51' },
      { key: 'topics[]52' },
      { key: 'topics[]53' },
      { key: 'topics[]54' },
      { key: 'topics[]55' },
      { key: 'topics[]56' },
      { key: 'topics[]57' },
      { key: 'topics[]58' },
      { key: 'topics[]59' },
      { key: 'topics[]60' },
      { key: 'topics[]61' },
      { key: 'topics[]62' },
      { key: 'topics[]63' },
      { key: 'topics[]64' },
      { key: 'topics[]65' },
      { key: 'transactionHash' },
      { key: 'logIndex', type: 'number' },
    ],
  },
  key: 'new_event',
  noun: 'Event',
  display: {
    label: 'New Event',
    description: 'Triggers when a new Event is emitted.',
    directions: "You'll get the same data that the RPC returns.",
    hidden: false,
    important: true,
  },
};
